[package]
name = "rs_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmp = "0.5.0"
colored = "2.0.0"
keyboard-types = "0.6.2"
nalgebra = "0.32.2"
rand = "0.8.5"
text_io = "0.1.12"

